title: Senator Olorunnisola
description: Junior Software Developer
site_title: 'Senator_dev'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: senator-dev
blog_url: https://www.Senator-dev.blogspot.com
email: senatoreniola@gmail.com
discord_username: senator_dev
twitter_username: senator_dev
instagram_username: senator_dev

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
