title: Senator Olorunnisola
description: Junior Software Developer
site_title: 'Senator_dev'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: senator-dev
blog_url: https://senator-dev.blogspot.com
email: senatoreniola@gmail.com
twitter_username: senator_dev
instagram_username: senator_dev
linkedin_username: senator-dev

# absolute or relative
profile_picture: assets/images/pre.jpg

# Google Analytics ID
google_analytics: G-8E9990JJRE
